### ISSUE TITLE
EDX Multipart Crash bug with buttons

### ISSUE THREAD

**Issue by BrisingrAerowing** [HrznStudio/EDX-Issues-Feedback#19]
#### Issue Description:
Crash when having two buttons in a single block space and accidentally clicking one

#### What happens:
Crash

#### What you expected to happen:
Either the button worked or nothing.

#### How to reproduce:
Place two buttons in a single block space and click one.

#### Affected Versions (Do *not* use "*latest*"):

- EDX Core (if applicable): -
- EDX Multipart (if applicable): 1.1.1
- EDX Redstone (if applicable): -
- Forge: 2673
- Minecraft: 1.12.2

#### Crash report, if relevent
[Crash Log](https://gist.github.com/BrisingrAerowing/1d24c9f5ef2bee2d7ce6e355678d1b77)

**Comment by TheCodedOne** [comment]
Looks like its a MCMP bug, I've talked to ama about it hopefully we can figure out what on earth is going on

**Comment by TheCodedOne** [comment]
Fixed in latest MCMP build
